name: API JAVALIN WORKFLOW
on:
  push:
    branches: [ main, week12 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - # from github
        name: Build and install myLibrary
        run: |
          cd ./myLibrary/library
          mvn clean install
      -
        name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: ./week13/reactiii
      -
        # https://docs.docker.com/build/ci/github-actions/tr
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: week13/reactiii
          file: week13/reactiii/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/3sem:latest
          